<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMInb3HD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMInb3HD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMInb3HD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMInb3HD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMInb3HD\App_KernelDevDebugContainer([
    'container.build_hash' => 'MInb3HD',
    'container.build_id' => '1e169d05',
    'container.build_time' => 1598345901,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMInb3HD');
